Ashwat's pull request
COPS-IITBHU/csoc-2021-algorithms pull request #18
Opened 2021-06-01 18:24 UTC by iamaks287

bubble sort in c++

2021-06-01 20:03 UTC, king-11 requested changes

2021-06-01 20:03 UTC, king-11 commented on c++/bubble_sort.cpp
> +    for (int i = 0; i < s - (step-1); ++i)
This is doesn't seem right

at `step = 0`, `i` will go until `s` which is array out of bounds it should be `s - step - 1`

2021-06-01 20:03 UTC, king-11 commented on c++/bubble_sort.cpp
> +void bubbleSort(int arr[], int s)
Move function definition after main just keep the function declaration here.

2021-06-02 04:49 UTC, iamaks287 commented
I have made the suggested changes

2021-06-02 04:50 UTC, king-11 approved these changes

2021-06-02 04:50 UTC, king-11 commented
Have you tested your program this time?

2021-06-02 05:42 UTC, iamaks287 commented
Yeah i have tested it and it's working fine

2021-06-06 19:20 UTC, merged