added linear search in C++
COPS-IITBHU/csoc-2021-algorithms pull request #3
Opened 2021-05-31 07:50 UTC by sidkhuntia

I have added the code for linear search in C++.

2021-06-01 10:06 UTC, king-11 requested changes

2021-06-01 10:06 UTC, king-11 commented on c++/binary_search_sidkhuntia.cpp
> +const lli mod = 1e9 + 7;
This also has no correlation to searching remove this

2021-06-01 10:06 UTC, king-11 commented on c++/binary_search_sidkhuntia.cpp
> +    cin.tie(NULL);
Again not a contest so can remove these too

2021-06-01 10:06 UTC, king-11 commented on c++/binary_search_sidkhuntia.cpp
> +int binarySearch(int arr[], int l, int r, int x)
I would prefer having function declaration above main while the function declaration goes below main as it makes sense to have main above all

2021-06-01 10:06 UTC, king-11 commented on c++/binary_search_sidkhuntia.cpp
> +    int n = sizeof(arr) / sizeof(arr[0]);
Rather prefer taking a random `arr` and `n` as input

2021-06-01 10:06 UTC, king-11 commented on c++/binary_search_sidkhuntia.cpp
> +        ? cout << "Not available"
`Not available` sounds not so correct `Not Found` may sound better

2021-06-01 10:06 UTC, king-11 commented on c++/linear_search_sidkhuntia.cpp
> +            return i;
We can keep `i` as a local declaration

2021-06-01 10:06 UTC, king-11 commented on c++/linear_search_sidkhuntia.cpp
> +    int n = sizeof(arr) / sizeof(arr[0]);
Same as binary search

2021-06-01 10:06 UTC, king-11 commented on c++/linear_search_sidkhuntia.cpp
> +        ? cout << "Not available"
Rewording

2021-06-01 10:07 UTC, king-11 commented
Moreover please include only one algorithm in your PR :)

2021-06-03 11:05 UTC, sidkhuntia commented on c++/binary_search_sidkhuntia.cpp
> +#define f(i, n) for (int i; i < n; i++)
Can you please review now ?

2021-06-06 19:14 UTC, king-11 commented
@sidkhuntia updates on this you will have to make a new PR as the branch hasn't to non `main` and also ensure that algo is either binary or linear search only

2021-06-06 19:14 UTC, closed without merging